default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: url-shortener_development

test:
  <<: *default
  database: url-shortener_test

production:
  <<: *default
  database: url-shortener_production
  username: url-shortener
  password: <%= ENV['URL-SHORTENER_DATABASE_PASSWORD'] %>
